### PR TITLE
Changed proxy.pac installation to be automatic under OSX

### PR DESCRIPTION
**Pull request by etodanik**
The basic logic is as follows
1) We check if we're under OSX
2) If we are we check if the internet is being accessed through Wi-Fi or Ethernet (otherwise things won't work)
3) We apply proxy.pac to the appropriate port (Wi-Fi/Ethernet)
4) Proxy Ready. :)

### CODE REVIEW

**Comment by etodanik** [comment]
Anything missing here to be merged ?

**Comment by boutell** [comment]
Merged!

**Comment by boutell** [comment]
(Is it documented in the README that you don't have to mess with PAC files on a Mac now?)

**Comment by etodanik** [comment]
Nope. I think it can stay there, but only if the script itself can't do the setting (maybe add a notice that this is an extra step)?

**Comment by boutell** [comment]
Covered it. Thanks.

On Fri, Jan 24, 2014 at 1:32 PM, Danny Povolotski
notifications@github.comwrote:

> Nope. I think it can stay there, but only if the script itself can't do
> the setting (maybe add a notice that this is an extra step)?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/punkave/zoltar/pull/14#issuecomment-33248332
> .

## 

Tom Boutell
Lead Developer
P'unk Avenue
215 755 1330
punkave.com
window.punkave.com

**Pull request merged**
